name: CI

env:
  NODE_OPTIONS: --max-old-space-size=6144

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: ${{ github.event_name != 'push' }}

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: corepack enable
      - name: Install dependencies
        run: pnpm install
      - name: Format check
        run: pnpm run format
      - name: Type check
        run: pnpm run typecheck
      - name: Lint
        run: pnpm run lint
      # - name: Test unit
      #   run: pnpm run test:unit
      # - name: Test e2e
      #   run: pnpm run test:e2e
